### ISSUE TITLE
[Miranum Integration Showcase] - Use miranum workers with DigiWF

### ISSUE THREAD

**Issue by lmoesle** [Miragon/miragon-consulting#37]
- [x] Description created
- [ ] Reviewed by peer: @Hafflgav 
- [ ] Prioritised

# Description

Create a showcase to use a Miranum worker together with DigiWF.

- **Create a DigiWF Integration using a Miranum Worker**: Create a simple Miranum Worker that sends Emails and use it as a DigiWF Integration. The worker could be very similar to the [DigiWF Email Integration](https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-integrations/digiwf-email-integration)
- **Trigger the Miranum Worker from Spring Cloud Stream**: The Miranum Worker will get called from a Spring Cloud Stream Event. We should implement a Spring Boot Starter that triggers a Miranum Worker directly from a Message Event.
- **Create an example bpmn process**: Create an example bpmn process with a json schema form that sends emails using the miranum worker

**Additional Information**

- The bridge between Spring Cloud Stream and Miranum Worker was once implemented as a Spring Boot Starter and later removed. See https://github.com/Miragon/digiwf-core/tree/feature/digiwf-integration-lib-before-removing-it for the initial implementation
- You can checkout the digiwf documentation on [how to implement integration services](https://digiwf.oss.muenchen.de/integrations/concept/integration-service.html#modellierung)
- You can create a custom example process or use the example digiwf uses -> https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-engine/digiwf-engine-service/src/main/resources/prozesse/example/email-integration

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Implement a miranum worker that sends emails
- [ ] Create a spring boot starter to connect the miranum worker to digiwf
- [ ] Create documentation
- [ ] Write a blogpost
```
